[package]
name = "arcana"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mage"
path = "src/mage/src/main.rs"

[workspace]
members = [
    "src/shared",
    "src/mage",
]

[dependencies]
shared = { path = "src/shared"}
