[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { version = "0.2.17", features = ["i128"] }
regex = "1.10.6"

[features]
default = ["interpreter"]
interpreter = []
